speechbubble/speechbubble/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from filebrowser.sites import site

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('speechbubble.views',
                       (r'^$', 'home'),
                       (r'^search/$', 'search'),
)

urlpatterns += patterns('django.views.generic.simple',
                        # Example:
                        # (r'^speechbubble/', include('speechbubble.foo.urls')),

                        # (r'^$', 'direct_to_template', {'template': 'index.html'}),

                        (r'^', include('speechbubble.voca.urls')),

                        (r'^admin/filebrowser/', include(site.urls)),
                        (r'^tinymce/', include('tinymce.urls')),
                        #    (r'^news/', include('django_simple_news.urls')),
                        url(r'^pages/', include('pages.urls')),
                        (r'^newsletter/', include('speechbubble.campaign.urls')),

                        # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
                        # to INSTALLED_APPS to enable admin documentation:
                        # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

                        # Uncomment the next line to enable the admin:
                        (r'^admin/', admin.site.urls),
                        # url(r'^', include('cms.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$',
                            'django.views.static.serve',
                            {'document_root': settings.MEDIA_ROOT})
                    ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

speechbubble/speechbubble/voca/models.py
import operator
from django.db import models
from datetime import datetime
from django.db.models import Q
from filebrowser.fields import FileBrowseField
from tinymce import models as tinymce_models
from photologue.models import ImageModel, Photo

# Create your models here.

SPEECH_TYPE_CHOICES = (
    ('recorded', 'Recorded'),
    ('artificial', 'Mainly Artificial'),
)

OS_CHOICES = (
    ('none', 'None'),
    ('dedicated', 'Dedicated'),
    ('windows', 'Windows'),
    ('macintosh', 'Macintosh'),
    ('mobile', 'Mobile Devices'),
    ('other', 'Other'),
)


class DraftManager(models.Manager):
    ''' Use this manager to get objects that have a draft field '''
    def get_query_set(self):
        return super(DraftManager, self).get_query_set().filter(draft=False)

    def all_with_draft(self):
        return super(DraftManager, self).get_query_set()

    def draft_set(self):
        return super(DraftManager, self).get_query_set().filter(draft=True)

    def get(self, *args, **kwargs):
        ''' if a specific record was requested, return it even if it's
        draft '''
        return self.all_with_draft().get(*args, **kwargs)
                     
    def filter(self, *args, **kwargs):
        ''' if pk was specified as a kwarg, return even
        if it's draft '''
        if 'pk' in kwargs:
            return self.all_with_draft().filter(*args, **kwargs)
        return self.get_query_set().filter(*args, **kwargs)


class DeviceImage(models.Model):
    device = models.ForeignKey('Device', related_name='images')
    image = FileBrowseField(
        max_length=200, 
        directory="/images/",
        extensions=['.jpg', '.jpeg', '.gif','.png','.tif','.tiff'],
        format='Image',
        blank=True, 
        null=True
    )


class SoftwareImage(models.Model):
    software = models.ForeignKey('Software', related_name='images')
    image = FileBrowseField(
        max_length=200, 
        directory="/images/", 
        extensions=['.jpg', '.jpeg', '.gif','.png','.tif','.tiff'],
        format='Image', 
        blank=True, 
        null=True
    )


class VocabularyImage(models.Model):
    vocabulary = models.ForeignKey('Vocabulary', related_name='images')
    image = FileBrowseField(
        max_length=200, 
        directory="/images/", 
        extensions=['.jpg', '.jpeg', '.gif','.png','.tif','.tiff'],
        format='Image', 
        blank=True, 
        null=True
    )


class DeviceType(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(DeviceType,self).save()

    class Meta:
        ordering = ['-id']


class ScanningIndication(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(ScanningIndication,self).save()


class PredictionEnhancement(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(PredictionEnhancement,self).save()

    class Meta:
        ordering = ['-id']


class AuditoryScanning(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(AuditoryScanning,self).save()

    class Meta:
        ordering = ['-id']


class LanguageLevel(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(LanguageLevel,self).save()

    class Meta:
        ordering = ['-id']


class OperatingSystem(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(OperatingSystem,self).save()

    class Meta:
        ordering = ['-id']


class Supplier(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True)
    address = tinymce_models.HTMLField()
    postcode = models.CharField(max_length=8, null=True, blank=True)
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    fax_number = models.CharField(max_length=50, null=True, blank=True)
    email_address = models.EmailField(null=True, blank=True)
    website_url = models.CharField(max_length=255, null=True, blank=True)
    bhta_member = models.BooleanField()
    switch_access = models.BooleanField()
    googlemap = models.URLField(null=True, blank=True)
    no_longer_trading = models.BooleanField()
    notes = tinymce_models.HTMLField(null=True, blank=True)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(Supplier,self).save()


class Document(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)
    file = models.FileField(upload_to='docs')
    supplier = models.ForeignKey(Supplier, null=True, blank=True)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(Document,self).save()


class Access(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(Access,self).save()

    class Meta:
        ordering = ['-id']


class SymbolLibrary(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(SymbolLibrary,self).save()


class WheelchairMount(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(WheelchairMount,self).save()


class Voice(models.Model):
    date_created = models.DateTimeField(editable=False)
    date_updated = models.DateTimeField(editable=False)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

    def save(self, **kwargs):
        if not self.id:
            self.date_created = datetime.now() # Edit created timestamp only if it's new entry
        self.date_updated = datetime.now()
        super(Voice,self).save()


class VocabularyManager(DraftManager):
    def search(self, terms):
        q_objects = []

        for term in terms:
            q_objects.append(Q(name=term))

        # Start with a bare QuerySet
        qs = self.get_query_set()

        # Use operator's or_ to string together all of your Q objects.
        return qs.filter(reduce(operator.or_, q_objects))


class Vocabulary(models.Model):
    VOCABULARY_TYPE_CHOICES = (
        ('topic', 'Mainly topic based'),
        ('syntax', 'Mainly syntax based'),
        ('scene', 'Visual scene based'),
    )

    LANGUAGE_REPRESENTATION_CHOICES = (
        ('text', 'Text only (letters, words, phrases)'),
        ('single', 'Text and single meaning symbols'),
        ('multi', 'Text and multi-meaning symbols'),
    )

speechbubble/speechbubble/campaign/forms.py
import csv
from django import forms
from django.utils.translation import ugettext as _
try:
    from django.utils.simplejson import simplejson as json
except ImportError:
    from django.utils import simplejson as json
    
class UploadForm(forms.Form):
    """
    validates that the uploaded file contains parseable json data.
    """
    file = forms.FileField()
    
    def clean_file(self):
        try:
            json.loads(self.cleaned_data['file'].read())
            self.cleaned_data['file'].seek(0)
            return self.cleaned_data['file']
        except Exception, e:
            try:
                reader = csv.reader(self.cleaned_data['file'].readlines())
                self.cleaned_data['file'].seek(0)
                return self.cleaned_data['file']
            except Exception, e:
                raise forms.ValidationError(_(u"uploaded file must contain json or csv data"))
        

class SubscribeForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
 

class UnsubscribeForm(forms.Form):
    email = forms.EmailField()

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
                <title>{% block title %}{% endblock %}</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<meta name="Description" content="GET PAGE DESCRIPTION" />
		<script src="/media/js/jquery/jquery-1.3.2.js" type="text/javascript"></script>
		<script src="/media/js/jquery/plugins/ui.core.js" type="text/javascript"></script>
		<script src="/media/js/jquery/plugins/ui.tabs.js" type="text/javascript"></script>
		<script type="text/javascript" src="/media/js/global.js"></script>

		<link href="/media/css/defaultstyles.css" rel="stylesheet" type="text/css" />
  		<link href="/media/css/printstyles.css" rel="stylesheet" type="text/css" media="print" />
		<!--[if lte IE 6]>
		<link rel="stylesheet" type="text/css" href="/media/css/LessThanOrEqualToIE6.css" />
		<![endif]-->
		<!--[if IE 7]>
		<link rel="stylesheet" type="text/css" href="/media/css/IE7.css" />
		<![endif]-->
		<!--[if IE 8]>
		<link rel="stylesheet" type="text/css" href="/media/css/IE8.css" />
		<![endif]-->
		{% block css %}{% endblock %}
		<link rel="stylesheet" href="/media/css/jquery/plugins/ui.tabs.css" type="text/css" media="print, projection, screen" />
		<link rel="stylesheet" href="/media/css/jquery/plugins/jquery.lightbox-0.5.css" type="text/css" media="print, projection, screen" />
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4785216-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type =
'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(ga, s);
  })();

</script>

	</head>
	<body>
		<div id="pagewrapperouter">
		<div id="header">
			<a href="#searchanchor" class="skiplink">go to search</a>
			<a href="#contentanchor" class="skiplink">go to content</a>
			<div id="acelogo">
				<!--<a href="/">-->
                <a href="http://www.acecentre.org.uk">
					<img src="/media/img/acelogo_7_620.gif" width="120" height="48" alt="ACE Centre logo" />
				</a>
			</div>
		
		
			<!-- This upper horizontal nav section to be taken out as an include? -->
			<div id="searchbox">
				<a class="skiplink" name="searchanchor" id="searchanchor"></a>
				<form 
					action="/search/" 
					method="get" 
					id="searchformx"
				>
					<fieldset>
						<label for="sitesearch" accesskey="4">sitesearch</label>
						<input name="q" id="sitesearch" type="text" />
						<input 
							src="/media/img/searchbutton_7_831.gif" 
							alt="search this website" 
							id="sitesearchFormSubmit" 
							class="formbutton" 
							value="search" 
							type="image" 
						/>
					</fieldset>
				</form>
			</div>
			<ul>
				<li><a href="/pages/about/">about this site</a></li>
				<!--<li><a href="/sitemap/">sitemap</a></li>-->
				<li class="noline"><a href="/pages/contact/">contact us</a></li>
			</ul>
			<!-- end proposed include -->
			
		</div>
	
		{% block body %}{% endblock %}
	

		<div id="footer">
			<ul>
				<li><a href="/pages/legal/">legal</a></li>
				<li><a href="/pages/accessibility/">accessibility</a></li>
				<li><a href="/admin/">admin login</a></li>
				<li><a href="/pages/disclaimer/">disclaimer</a></li>
				<li class="noline"><a href="mailto:enquiries@acecentre.org.uk">enquiries@acecentre.org.uk</a></li>
			</ul>
			<p>created and maintained by the <a class="acelink" href="http://www.acecentre.org.uk">ace centre advisory trust</a>, charity no 1040868</p>
                <div id="tinylogos" class="clear">
				<a href="http://www.nominettrust.org.uk/"><img src="/media/img/nominetlogo.gif" width="93" height="33" alt="Nominet Logo" /></a>
				</div>

			</div>
		</div>
	</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block title %}SpeechBubble{% endblock %}
{% block css %}
<link href="/media/css/homepagestyles.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block body %}
<div id="contenthomepage">

<div id="titlebar">
			<div class="titlebarLH">
				<img src="/media/img/singlepixelgif.gif" height="20px" alt="*"/>
			</div>
	</div>
	<div id="splashgraphicgirl">
    	<div id="splashtext"><img src="/media/img/logoright.gif" alt="speechbubble - all about communication aids"/></div>
    </div>

<!--<div id="splashgraphiccontainer">
	<div id="splashgraphicleft"><img src="/media/img/combilogo2.gif" alt="speechbubble - all about communication aids"/></div>
    </div> -->
   	
 
 	<a class="skiplink" name="contentanchor" id="contentanchor"></a>
	
    <div id="lefthomecontent">
    <!--<div class="shiftup">-->
    <div class="indentedtextfirstpara">
     <p class="largerplus">If you need help with spoken communication because of a disability, this website can give you an idea of what's on offer, with details of nearly every communication aid available in the UK - and it's all searchable!</p>
    <p class="larger"><a href="/pages/en/help/">Help! Where do I start?</a></p>
        </div>

		<div class="devicebox">
        <div class="cbb">
        <div class="centeringdivfordevicecontent">
        <p class="subhead">CHOOSE A</p>
		<h3 class="largest">COMMUNICATION AID</h3>
        <!--<p>If you know the name of the aid you're looking for, select it from the list below.</p>-->
		<form action="" method="get" class="homeselectdevice" name="deviceSelect">
			<p>
			<!--<label for="devices" class="formlabel">search by name</label>-->
			<select 
				name="devices" 
				id="devices"
				onchange="document.location.href=document.deviceSelect.devices.options[document.deviceSelect.devices.selectedIndex].value">
				<option value="">select an aid</option>
			{% for device in device_list %}
				<option value="/device/{{ device.slug }}/">{{ device.name }}</option>
			{% endfor %}
			</select>
			</p>
            <p class="lightblue">OR</p>
            <div class="indentedtextfirstpara">
			<p class="larger"><a href="/devices/search">search by feature</a></p>
            <p class="lightbluesmaller">OR</p>
			<p class="larger"><a href="/devices/?x=43&y=12">compare communication aids</a></p>
            </div>
		</form>
        </div>
	    </div>
        </div>

        <div class="indentedtextlastpara">
                <h3>More Searches...</h3>
        </div>       
		<div class="RHbluebox">
	    <div class="cbb">
        <div class="centeringdivforRHblueboxcontent">
        <p class="subhead">Find</p>
		<h3 class="smaller">SOFTWARE</h3>
		<form action="" method="get" class="homeselect" name="softwareSelect">
			<p>
			<!--<label for="software" class="formlabel">search</label>-->
			<select 
				name="software" 
				id="software"
				onchange="document.location.href=document.softwareSelect.software.options[document.softwareSelect.software.selectedIndex].value"
			>
				<option value="">select software</option>
			{% for software in software_list %}
				<option value="/software/{{ software.slug }}/">{{ software.name }}</option>
			{% endfor %}
			</select>
			</p>
			<p><a href="/software/search/">search by feature</a></p>
		</form>
		</div>
		</div>
        </div>
        
		<div class="RHbluebox">
	    <div class="cbb">
        <div class="centeringdivforRHblueboxcontent">
        <p class="subhead">FIND A</p>
		<h3 class="smaller">VOCABULARY</h3>
		<form action="" method="get" class="homeselect" name="vocabularySelect">
			<p>
			<!--<label for="vocabularies" class="formlabel">search</label>-->
			<select 
				name="vocabularies" 
				id="vocabularies"
				onchange="document.location.href=document.vocabularySelect.vocabularies.options[document.vocabularySelect.vocabularies.selectedIndex].value"
			>
				<option value="">select vocabulary</option>
			{% for vocabulary in vocabulary_list %}
				<option value="/vocabulary/{{ vocabulary.slug }}/">{{ vocabulary.name }}</option>
			{% endfor %}
			</select>
			</p>
			<p><a href="/vocabularies/search/">search by feature</a>		</p>
		</form>
		</div>
		</div>
        </div>
    
        
		<div class="RHbluebox">
	    <div class="cbb">
        <div class="centeringdivforRHblueboxcontent">
        <p class="subhead">CONTACT A</p>
		<h3 class="smaller">SUPPLIER</h3>
		<form action="" method="get" class="homeselect" name="supplierSelect">
			<p>
			<!--<label for="vocabularies" class="formlabel">search</label>-->
			<select 
					name="suppliers" 
				id="suppliers"
				onchange="document.location.href=document.supplierSelect.suppliers.options[document.supplierSelect.suppliers.selectedIndex].value"
			>
				<option value="">choose a supplier</option>
			{% for supplier in supplier_list %}
				<option value="/supplier/{{ supplier.slug }}/">{{ supplier.name }}</option>
			{% endfor %}
			</select>
			</p>
			<p><a href="/suppliers/">list all suppliers</a></p>
		</form>
		</div>
		</div>
        </div>

        
        
       <!--</div>--> 
        
    </div>







<div id="righthomecontent">

	
    		<div class="adbox">
            <div class="cbb orange">
            <div class="centeringdivfororangeboxcontent">
            <h3 class="smallerwhite">WE CAN HELP</h3>
			<a href="http://www.acecentre.org.uk/"><div class="adpic">
            <p>Link to the ACE Centre</p>
			</div></a>
            <p class="subheadwhite">Unbiased communication aid assessments and training</p>
            <p class="subheadwhite"><a href="http://www.acecentre.org.uk/">CLICK FOR DETAILS</a></p>
            </div>
            </div>
            </div>
			
            <!--
    		<div class="adbox">
            <div class="cbb orange">
            <div class="centeringdivfororangeboxcontent">
            <h3 class="smallerwhite">iPads &amp; AAC</h3>
			<a href="http://bit.ly/pJGDvV"><div class="adpic">
            <p>Link to the ACE Centre</p>
			</div></a>
            <p class="subheadwhite">Unmissable Network Day</p>
            <p class="subheadwhite">20 October, Oxford</p>
            <p class="subheadwhite"><a href="http://bit.ly/pJGDvV">CLICK FOR DETAILS</a></p>
            </div>
            </div>
            </div>
            -->
                        
			<div id="formindent">
            <h3 class="signup">SIGN UP</h3>
            <p class="subhead">Our free quarterly email update!</p>
            <p>With all that's new about communication aids</p>
            <form 
					action="/newsletter/subscribe/" 
					method="post" 
					id="submitformx"
				>

					<fieldset>
						<label for="id_name" accesskey="3" class="formlabel">name:</label>
						<input name="name" id="id_name" type="text" /></ br>
						<label for="id_email" accesskey="4" class="formlabel">email:</label>
						<input name="email" id="id_email" type="text" /></ br>
						<input 
							src="/media/img/signup_button.gif" 
							alt="sign up for our monthly email" 
							id="emailFormSubmit" 
							class="signupbutton" 
							value="search" 
							type="image" 
						/>
					</fieldset>
				</form>
                <p>We won't share your details with anyone else. Ever.</p>
				</div>
                
                
</div>
</div>

<div class="clear"></div>
{% endblock %}

templates/onecol.html
{% extends "base.html" %}
{% block body %}
				<div id="titlebar">
                    <div class="titlebarLH">
                        <h1>{% block title %}{% endblock %}</h1>
                    </div>
				</div>
				
				<!-- This breadcrumb section to be taken out as an include? -->
				<div id="breadcrumb">
                                        {% block breadcrumbs %}{% endblock %}
				</div>
				<!-- end proposed include -->
                
                <div id="contentcentre" class="contentonecol">
                    <a class="skiplink" name="contentanchor" id="contentanchor"></a>
                    {% block content %}{% endblock %}
                </div>
                
  				<div id="straplinebar">
					<div class="straplinebarLH">
						<p>giving the gift of communication</p>
					</div>
				</div>
									
	<div class="clear"></div>
{% endblock %}

templates/threecol.html
{% extends "base.html" %}
{% block body %}
<div id="contentleft">
	<div id="printhomehelp">
    		<div id="printiconbox"><a href="javascript:window.print();">Print this page</a></div>
		<div id="homeiconbox"><a href="/">Home</a></div>
		<div id="helpiconbox"><a href="/pages/en/help/">Help!</a></div>
	</div>
	{% block contentleft %}{% endblock %}
</div>
<div id="contentcentreandrightwrapper">
	<div id="contentcentrewrapper">	
		<div id="titlebar">
			<div class="titlebarLH">
				<h1>{% block title %}{% endblock %}</h1>
			</div>
		</div>
		<!-- This breadcrumb section to be taken out as an include? -->
		<div id="breadcrumb">
			{% block breadcrumbs %}{% endblock %}
		</div>
		<!-- end proposed include -->
		<div id="contentcentre">
			<a class="skiplink" name="contentanchor" id="contentanchor"></a>
			{% block content %}{% endblock %}
		</div>
		<div id="straplinebar">
			<div class="straplinebarLH">
				<p>giving the gift of communication</p>
			</div>
		</div>
	</div>
	<div id="contentright">
		{% block rightcontent %}{% endblock %}
	</div>
	<div class="clear"></div>
</div><!-- contentcentreandright -->
{% endblock %}

templates/twocol.html
{% extends "base.html" %}
{% block body %}
<div id="contentleft">
	{% block contentleft %}<p>Left content</p>{% endblock %}
</div>

<div id="contenttwocol">
	<div id="titlebar">
                   <div class="titlebarLH">
                       <h1>{% block title %}{% endblock %}</h1>
                   </div>
	</div>
			
	<!-- This breadcrumb section to be taken out as an include? -->
	<div id="breadcrumb">
		{% block breadcrumbs %}{% endblock %}
	</div>
	<!-- end proposed include -->

	<div id="contentcentre">
		<a class="skiplink" name="contentanchor" id="contentanchor"></a>
		{% block content %}{% endblock %}
	</div>
               
  	<div id="straplinebar">
		<div class="straplinebarLH">
			<p>giving the gift of communication</p>
		</div>
	</div>
								
	<div class="clear"></div>
</div>
{% endblock %}